version: "3"
services:
    db:
        image: "postgres"
        container_name: "bootcamp-db"
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=bootcamp-db
        ports:
            - "5432:5432"
