server:
  port: 8080

spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://db:5432/bootcamp-db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create